export const CURRENT_LOADED = "CURRENT_LOADED"
export const TOTAL_LOADED = "TOTAL_LOADED"
export const COUNTRIES_LOADED = "COUNTRIES_LOADED"
export const COUNTRY_LOADED = "COUNTRY_LOADED"
export const HISTORICAL_LOADED = "HISTORICAL_LOADED"
export const COUNTRY_PREDICTION = "COUNTRY_PREDICTION"
export const COUNTRY_METRIC = "COUNTRY_METRIC"

export const NEWS_LOADED = "NEWS_LOADED"
